- hosts:              webservers
  gather_facts:       no
  tasks:
    - name:           Install fail2ban
      apt:            pkg=fail2ban update_cache=yes
      sudo:           yes
    - name:           Configure fail2ban
      template:       src=fail2ban/${item} dest=/etc/fail2ban/${item} mode=0644
      with_items:
        - jail.local
        - filter.d/apache-wordpress.local
      sudo:           true
    - name:           Configure iptables-persistent
      template:       src=iptables/${item} dest=/etc/${item} mode=0644
      with_items:
        - init.d/iptables-persistent
        - default/iptables-persistent.conf
        - iptables/rules
        - iptables/ipv6_rules
      sudo:           true
    - name:           Register iptables-persistent init.d script
      command:        update-rc.d iptables-persistent defaults
      sudo:           true
